---
- name: add key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.2.asc
    state: present
  tags: install

- name: add repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Apt update2
  apt:
    update_cache: yes

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
    allow_unauthenticated: yes
  tags: install

- name: Start and Enable MongoDB
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install
