---
plugin: yc_compute
folders:
  - b1gqs7d884s24jlealvk
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: /Users/i.ryzhikov/otus/yc_cloud_service_key/key.json
hostnames:
  - fqdn
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
groups:
   app: labels['tags'] == 'reddit-app'
   db: labels['tags'] == 'reddit-db'
